import esbuild from "esbuild";
import process from "process";

const banner = `/*
Wikipedia Importer — an Obsidian plugin.
This file is generated by esbuild; see the plugin/ and src/ directories in the repo.
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["plugin/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr"
	],
	// Browser platform keeps the bundle free of Node built-ins so the
	// plugin can run on mobile as well as desktop.
	platform: "browser",
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js"
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
